import { jsPDF } from 'jspdf';

interface ExportOptions {
  format?: 'pdf' | 'png' | 'jpg';
  quality?: number;
  orientation?: 'portrait' | 'landscape';
}

class PDFExporter {
  private defaultOptions: ExportOptions = {
    format: 'pdf',
    quality: 1.0,
    orientation: 'landscape',
  };

  async exportPosterToPDF(
    posterData: {
      title: string;
      subtitle?: string;
      content: string[];
      imageUrl?: string;
    },
    options: ExportOptions = {}
  ): Promise<void> {
    const opts = { ...this.defaultOptions, ...options };
    const doc = new jsPDF({
      orientation: opts.orientation,
      unit: 'mm',
      format: 'a4',
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;

    if (posterData.imageUrl) {
      try {
        const imgProps = doc.getImageProperties(posterData.imageUrl);
        const imgWidth = pageWidth - margin * 2;
        const imgHeight = (imgProps.height * imgWidth) / imgProps.width;
        doc.addImage(posterData.imageUrl, 'PNG', margin, margin, imgWidth, Math.min(imgHeight, pageHeight * 0.4));
      } catch (error) {
        console.warn('Could not load image:', error);
      }
    }

    doc.setFontSize(28);
    doc.setFont('helvetica', 'bold');
    doc.text(posterData.title, margin, posterData.imageUrl ? 80 : 40);

    if (posterData.subtitle) {
      doc.setFontSize(14);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 100, 100);
      doc.text(posterData.subtitle, margin, posterData.imageUrl ? 90 : 50);
      doc.setTextColor(0, 0, 0);
    }

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    const contentLines = doc.splitTextToSize(posterData.content.join('\n'), pageWidth - margin * 2);
    let yPos = posterData.imageUrl || posterData.subtitle ? 110 : 70;
    
    contentLines.forEach((line: string) => {
      if (yPos > pageHeight - margin) {
        doc.addPage();
        yPos = margin;
      }
      doc.text(line, margin, yPos);
      yPos += 7;
    });

    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by PitchCube - ${new Date().toLocaleDateString()}`, margin, pageHeight - 10);

    doc.save(`pitchcube-${posterData.title.replace(/\s+/g, '-').toLowerCase()}.pdf`);
  }

  async exportToPNG(element: HTMLElement, filename: string): Promise<void> {
    const canvas = await this.htmlToCanvas(element);
    const link = document.createElement('a');
    link.download = `${filename}.png`;
    link.href = canvas.toDataURL('image/png');
    link.click();
  }

  async exportToJPG(element: HTMLElement, filename: string, quality = 0.9): Promise<void> {
    const canvas = await this.htmlToCanvas(element);
    const link = document.createElement('a');
    link.download = `${filename}.jpg`;
    link.href = canvas.toDataURL('image/jpeg', quality);
    link.click();
  }

  private async htmlToCanvas(element: HTMLElement): Promise<HTMLCanvasElement> {
    const html2canvas = (await import('html2canvas')).default;
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      allowTaint: true,
      backgroundColor: '#ffffff',
    });
    return canvas;
  }

  async exportMultiPagePDF(
    pages: Array<{
      title: string;
      content: string;
      imageUrl?: string;
    }>,
    options: ExportOptions = {}
  ): Promise<void> {
    const opts = { ...this.defaultOptions, ...options };
    const doc = new jsPDF({
      orientation: opts.orientation,
      unit: 'mm',
      format: 'a4',
    });

    pages.forEach((page, index) => {
      if (index > 0) doc.addPage();

      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;

      if (page.imageUrl) {
        try {
          const imgProps = doc.getImageProperties(page.imageUrl);
          const imgWidth = pageWidth - margin * 2;
          const imgHeight = (imgProps.height * imgWidth) / imgProps.width;
          doc.addImage(page.imageUrl, 'PNG', margin, margin, imgWidth, Math.min(imgHeight, pageHeight * 0.4));
        } catch (error) {
          console.warn('Could not load image:', error);
        }
      }

      doc.setFontSize(24);
      doc.setFont('helvetica', 'bold');
      doc.text(page.title, margin, page.imageUrl ? 80 : 40);

      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      const contentLines = doc.splitTextToSize(page.content, pageWidth - margin * 2);
      let yPos = page.imageUrl ? 100 : 60;

      contentLines.forEach((line: string) => {
        if (yPos > pageHeight - margin) {
          doc.addPage();
          yPos = margin;
        }
        doc.text(line, margin, yPos);
        yPos += 7;
      });
    });

    doc.save('pitchcube-presentation.pdf');
  }
}

export const pdfExporter = new PDFExporter();
export default pdfExporter;
